### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/dapp-sidedao#15]
* [ ] Choose domain name
* [ ] Setup github pages 
* [ ] Release branch?
* [ ] Alchemy API observability
  * [ ] Restrict to specific domains? Will this affect unit tests
* [ ] Final frontend UX tweaks

**Comment by CedarMist** [comment]
If you want to enable Sapphire ACL, we need more testing - the contract will only work with tokens on the same chain as the PollManager is deployed on.

**Comment by CedarMist** [comment]
Embed the polls in other pages in an iframe.

**Comment by CedarMist** [comment]
Start feedback loop with Jure,

**Comment by CedarMist** [comment]
Temporarily disable xchain
